package com.kamontat.gui;

import com.intellij.uiDesigner.core.GridLayoutManager;
import com.kamontat.model.github.User;
import com.kamontat.model.management.Location;

import javax.swing.*;
import java.awt.*;
import java.util.*;

import static javax.swing.SwingUtilities.invokeLater;

/**
 * @author kamontat
 * @version 1.0
 */
public class RepositoryPage extends JFrame {
	private ArrayList<User> all;
	private JPanel pane;
	private JTable table1;
	private JTextField textField1;
	private JButton addButton;
	private JButton addAllButton;
	
	private RepositoryPage(ArrayList<User> all) {
		setContentPane(pane);
		this.all = all;
	}
	
	private void compile(Window old) {
		pack();
		setMinimumSize(new Dimension(getWidth(), getHeight()));
		setLocation(Location.getCenterPage(old, this));
		setVisible(true);
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
	}
	
	public static void run(final Window oldPage, final ArrayList<User> all) {
		invokeLater(new Runnable() {
			@Override
			public void run() {
				new RepositoryPage(all).compile(oldPage);
			}
		});
	}
	
	{
		// GUI initializer generated by IntelliJ IDEA GUI Designer
		// >>> IMPORTANT!! <<<
		// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}
	
	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		pane = new JPanel();
		pane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
	}
	
	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return pane;
	}
}
