package com.kamontat.gui.containers;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.kamontat.exception.RequestException;
import com.kamontat.gui.components.AccountPanel;
import com.kamontat.model.github.GHAccount;
import com.kamontat.model.management.Location;
import com.kamontat.model.management.Size;
import com.kamontat.server.GithubLoader;

import javax.swing.*;
import java.awt.*;
import java.util.*;

import static javax.swing.SwingUtilities.invokeLater;

/**
 * @author kamontat
 * @version 1.0
 * @since 2/12/2017 AD - 7:42 PM
 */
public class AccountManagePage extends JFrame {
	private ArrayList<GHAccount> accounts;
	private JPanel panel1;
	private JScrollPane scrollPane;
	
	public AccountManagePage(ArrayList<GHAccount> accounts) {
		super("Account Manage Page");
		this.accounts = accounts;
		for (GHAccount account : accounts) {
			scrollPane.add(new AccountPanel(account));
		}
	}
	
	private void compile(Window oldPage) {
		setSize(Size.getDefaultPageSize());
		setLocation(Location.getCenterPage(oldPage, this));
		setVisible(true);
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
	}
	
	public static void run(final Window old, final ArrayList<GHAccount> accounts) {
		invokeLater(new Runnable() {
			@Override
			public void run() {
				new AccountManagePage(accounts).compile(old);
			}
		});
	}
	
	/**
	 * testing this gui
	 *
	 * @param args
	 * 		none used
	 */
	public static void main(String[] args) {
		ArrayList<GHAccount> accounts = new ArrayList<>();
		try {
			accounts.add(new GHAccount(GithubLoader.getGithubLoader().getUser("kamontat")));
		} catch (RequestException e) {
			e.printStackTrace();
		}
		
		AccountManagePage.run(null, accounts);
	}
	
	{
		// GUI initializer generated by IntelliJ IDEA GUI Designer
		// >>> IMPORTANT!! <<<
		// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}
	
	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		scrollPane = new JScrollPane();
		panel1.add(scrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
	}
	
	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel1;
	}
}
