package com.kamontat.gui.containers;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.kamontat.constant.FileExtension;
import com.kamontat.constant.HotKey;
import com.kamontat.controller.action.TableAction;
import com.kamontat.controller.loader.LoadProgress;
import com.kamontat.controller.loader.LoadingFile;
import com.kamontat.controller.loader.Task;
import com.kamontat.controller.menu.MenuBarController;
import com.kamontat.controller.menu.MenuUpdateListener;
import com.kamontat.controller.mouse.AbstractMouseAction;
import com.kamontat.controller.popup.Popup;
import com.kamontat.controller.popup.PopupController;
import com.kamontat.controller.table.AutoFitTable;
import com.kamontat.controller.table.TableInformationModel;
import com.kamontat.exception.RequestException;
import com.kamontat.model.github.User;
import com.kamontat.model.management.Device;
import com.kamontat.model.management.FileUtil;
import com.kamontat.model.management.Location;
import com.kamontat.model.management.Size;
import com.kamontat.server.GithubLoader;

import javax.swing.*;
import javax.swing.event.MenuEvent;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.net.URL;
import java.util.*;

import static javax.swing.SwingUtilities.invokeLater;

/**
 * @author kamontat
 * @version 1.0
 * @since 1/30/2017 AD - 5:57 PM
 */
public class UserPage extends JFrame {
	private final static String name1 = "With Text File";
	private final static String name2 = "With Organizations";
	
	{
		// GUI initializer generated by IntelliJ IDEA GUI Designer
		// >>> IMPORTANT!! <<<
		// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}
	
	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		pane = new JPanel();
		pane.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
		pane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		searchingField = new JTextField();
		panel1.add(searchingField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
		selectBtn = new JButton();
		selectBtn.setText("Select");
		panel1.add(selectBtn, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		myselfBtn = new JButton();
		myselfBtn.setText("Myself");
		panel1.add(myselfBtn, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		pane.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		final JScrollPane scrollPane1 = new JScrollPane();
		panel2.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		table = new AutoFitTable();
		scrollPane1.setViewportView(table);
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		pane.add(panel3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		nextBtn = new JButton();
		nextBtn.setText("Next");
		panel3.add(nextBtn, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		panel3.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
	}
	
	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return pane;
	}
	
	enum SelectedWay {
		TEXT, ORG
	}
	
	private JTextField searchingField;
	private JButton selectBtn;
	private JButton myselfBtn;
	private JButton nextBtn;
	private AutoFitTable<User> table;
	private JPanel pane;
	
	private TableInformationModel<User> model = new TableInformationModel<User>(User.getStringTitleVectorStatic());
	
	private UserPage() {
		super("User Page");
		setContentPane(pane);
		
		setMenuBar();
		settingTable();
		
		textFieldEvent();
		buttonEvent();
	}
	
	private void setMenuBar() {
		// left
		MenuBarController.Menu manageMenu = new MenuBarController.Menu("Management");
		// delete
		TableAction deleteAct = new TableAction.DeleteAction(table);
		manageMenu.addItem(new MenuBarController.Menu.Item(new HotKey(deleteAct.getName() + " selected"), deleteAct));
		// delete all
		TableAction deleteAllAct = new TableAction.DeleteAllAction(table);
		manageMenu.addItem(new MenuBarController.Menu.Item(new HotKey(deleteAllAct.getName()), deleteAllAct));
		// exit
		manageMenu.addItem(MenuBarController.Menu.Item.getExitMenu());
		
		MenuBarController.Menu multiSMenu = new MenuBarController.Menu("Multi-Selection");
		multiSMenu.addItem(new MenuBarController.Menu.Item(new HotKey(name1), new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				multiSelection(SelectedWay.TEXT);
			}
		}));
		
		multiSMenu.addItem(new MenuBarController.Menu.Item(new HotKey(name2), new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				multiSelection(SelectedWay.ORG);
			}
		}));
		
		// right
		final MenuBarController.Menu infoMenu = new MenuBarController.Menu("Information");
		final MenuBarController.Menu.Item sizeItem = new MenuBarController.Menu.Item("have: " + model.size() + " user(s)");
		infoMenu.addItem(sizeItem);
		infoMenu.addMenuUpdateListener(new MenuUpdateListener() {
			@Override
			public void updateTitle(MenuEvent e) {
				sizeItem.setText("have: " + model.size() + " user(s)");
			}
		});
		
		final MenuBarController.Menu settingMenu = new MenuBarController.Menu("Setting");
		
		MenuBarController.Menu[] lefts = MenuBarController.Menu.toArray(manageMenu, multiSMenu);
		MenuBarController.Menu[] rights = MenuBarController.Menu.toArray(infoMenu, settingMenu);
		
		setJMenuBar(new MenuBarController(lefts, rights));
	}
	
	private void buttonEvent() {
		final Window self = this;
		selectBtn.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				addUser(searchingField.getText());
			}
		});
		
		myselfBtn.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				GithubLoader.wait(myselfBtn);
				try {
					model.addRow(GithubLoader.getGithubLoader().getMyself());
				} catch (RequestException e1) {
					Popup.getLog(myselfBtn).error("Myself Not Found", "please check sign-in token or internet connecting clearly");
				}
				GithubLoader.done(myselfBtn);
			}
		});
		
		nextBtn.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				ArrayList<User> allUser = model.getAllData();
				if (!allUser.isEmpty()) {
//					RepositoryPage.run(self, GHAccount.convertAll(allUser));
					dispose();
				} else {
					Popup.getLog(self).info("No Github User", "must have at least 1 user");
				}
			}
		});
	}
	
	private void multiSelection(SelectedWay way) {
		if (way == SelectedWay.TEXT) multiSByText();
		else if (way == SelectedWay.ORG) multiSByOrg();
	}
	
	private void multiSByText() {
		final File file = LoadingFile.type(FileExtension.TXT).getFile(this);
		if (file != null) {
			ArrayList<String> arr = FileUtil.getContentByLine(file);
			loadingProgress(arr, "Loading... username (Text File)");
		}
	}
	
	private void multiSByOrg() {
		try {
			String name = Popup.getInput(this).question("Organization Name", "Enter the Organization Name?");
			GithubLoader.wait(this);
			User[] users = GithubLoader.getGithubLoader().getOrganization(name);
			GithubLoader.done(this);
			ArrayList<String> arr = new ArrayList<String>();
			for (User u : users) {
				arr.add(u.loginName);
			}
			
			loadingProgress(arr, "Loading... username (Organizations)");
		} catch (RequestException e) {
			e.printStackTrace();
		}
	}
	
	private void loadingProgress(final ArrayList<String> arr, String title) {
		final Component self = this;
		final LoadProgress loadPage = new LoadProgress(this, title, arr.size());
		loadPage.setTask(new Task() {
			@Override
			public void whenUpdate(Object oldValue, Object newValue) {
				int maximum = loadPage.getMax();
				int progress = (Integer) newValue;
				int percent = (progress * 100) / maximum;
				String message = String.format("loading: %s (%d%%).\n", getLabel(), percent);
				loadPage.set(message, progress);
			}
			
			@Override
			public void progress() {
				for (String name : arr) {
					update(name, 1);
					addUser(name);
					if (loadPage.isCancel()) break;
				}
			}
			
			@Override
			public void ifDone() {
				Popup.getLog(self).info("Loaded User", "there are " + arr.size() + " user(s)");
			}
		});
	}
	
	private void textFieldEvent() {
		searchingField.setToolTipText("Enter github username");
		searchingField.addActionListener(new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				addUser(searchingField.getText());
				searchingField.setText("");
			}
		});
	}
	
	private void addUser(String name) {
		GithubLoader.wait(this);
		User user = null;
		try {
			user = GithubLoader.getGithubLoader().getUser(name);
			model.addRow(user);
		} catch (RequestException e) {
			Popup.getLog(selectBtn).error("User Not Found", "please check user name clearly");
		}
		GithubLoader.done(this);
	}
	
	private void settingTable() {
		table.setModel(model);
		settingPopup();
		table.addMouseListener(new AbstractMouseAction() {
			
			@Override
			public void tripleClick(MouseEvent e) {
				table.updateSelected(e.getPoint());
				for (int i = 0; i < table.getColumnCount(); i++) {
					try {
						URL url = (URL) table.getValueAt(row(), i);
						Device.openWeb(url);
					} catch (ClassCastException ignore) {
					}
				}
			}
			
			@Override
			public void rightClick(MouseEvent e) {
				table.updateSelected(e.getPoint());
				
				if (e.isPopupTrigger()) {
					table.showPopup(e);
				}
			}
			
			private int row() {
				return table.getSelectedRow();
			}
		});
	}
	
	private void settingPopup() {
		table.addPopup(PopupController.getInstance());
		// information action
		table.addTableAction(new TableAction.InfoAction(this, table));
		// copy action
		table.addTableAction(new TableAction.CopyAction(table));
		// delete action
		table.addTableAction(new TableAction.DeleteAction(table));
		// delete all action
		table.addTableAction(new TableAction.DeleteAllAction(table));
	}
	
	private void compile(Window oldPage) {
		setSize(Size.getDefaultPageSize());
		setLocation(Location.getCenterPage(oldPage, this));
		setVisible(true);
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
	}
	
	public static void run(final Window old) {
		invokeLater(new Runnable() {
			@Override
			public void run() {
				new UserPage().compile(old);
			}
		});
	}
}
